services:
  app:
    build:
      context: ./
      dockerfile: cmd/isit/Dockerfile
    container_name: isit
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static  # 📌 Добавляем монтирование папки static
    networks:
      - app_network

  postgres:
    container_name: isit_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=isit
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db:
    driver: local
