server:
  url: "0.0.0.0:8080"

database:
  user: user
  password: password
  host: isit_db
  port: 5432
  db_name: isit
  ssl_mode: disable

logger:
  sink: stdout
  level: debug

jwt:
  secret_key: "supersecretkeyforjwt"
  expiration_time: 7200